name: GEOLOOP BUILDER

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.1

    - name: Instalar dependências
      run: |
        pip install -r builder_ai/requirements.txt

    - name: Executar GEOLOOP AI
      run: python builder_ai/geo_ai_executor.py

    - name: Commit automático dos arquivos gerados
      run: |
        git config user.name "geo-loop-bot"
        git config user.email "geo@loop.ai"
        git add LOG.txt RELATORIO_GERAL.txt
        git commit -m "Atualização automática dos relatórios"
        git push
