name: GEOLOOP BUILDER

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências (se existirem)
      run: |
        pip install -r builder_ai/requirements.txt || true

    - name: Executar GEOLOOP AI
      run: python builder_ai/geo_ai_executor.py

    - name: Commit automático das melhorias
      run: |
        git config --global user.name "Geoloop Builder"
        git config --global user.email "geoloop@auto.ai"
        git add .
        git commit -m "GEOLOOP_BUILDER_AI: melhorias automáticas" || echo "Nada novo para commit"
        git push || echo "Nada novo para enviar"
