name: GEOLOOP BUILDER

on:
  schedule:
    - cron: "0 * * * *"  # Executa a cada hora
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências (se existirem)
      run: |
        pip install -r requirements.txt || echo "Sem dependências adicionais"

    - name: Executar GEOLOOP AI
      run: |
        python geo_ai_executor.py

    - name: Commit automático das melhorias
      run: |
        git config user.name "geoloop-ai"
        git config user.email "geoloop@users.noreply.github.com"
        git add .
        git commit -m "Auto melhoria via GEOLOOP AI"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
