name: GEOLOOP BUILDER

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout do repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Executar GEOLOOP AI
      run: python builder_ai/geo_ai_executor.py

    - name: Commit automático dos arquivos gerados
      run: |
        git config user.name "geo-loop-bot"
        git config user.email "geo@loop.ai"
        git add LOG.txt RELATORIO_GERAL.txt
        git commit -m "Atualização automática dos relatórios GEOLOOP" || echo "Nada novo para commitar"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
