import os
import json
from datetime import datetime

# Diretório com os dados dos países
PAISES_DIR = "countries"

# Arquivos de saída
LOG_FILE = "LOG.txt"
RELATORIO_FILE = "RELATORIO_GERAL.txt"

def carregar_paises():
    paises = []
    for filename in os.listdir(PAISES_DIR):
        if filename.endswith(".json"):
            path = os.path.join(PAISES_DIR, filename)
            try:
                with open(path, "r", encoding="utf-8") as f:
                    dados = json.load(f)
                    paises.append(dados)
            except Exception as e:
                print(f"Erro ao ler {filename}: {e}")
    return paises

def gerar_relatorio(paises):
    relatorio = []
    for pais in paises:
        nome = pais.get("nome", "N/A")
        populacao = pais.get("populacao", "N/A")
        pib = pais.get("pib", "N/A")
        regime = pais.get("regime_governo", "N/A")
        relatorio.append(f"{nome} | População: {populacao} | PIB: {pib} | Regime: {regime}")
    return "\n".join(relatorio)

def salvar_arquivo(caminho, conteudo):
    with open(caminho, "w", encoding="utf-8") as f:
        f.write(conteudo)

def main():
    paises = carregar_paises()
    if not paises:
        print("Nenhum país carregado.")
        return

    print(f"{len(paises)} países processados.")

    salvar_arquivo(LOG_FILE, f"[{datetime.now()}] GEOLOOP BUILDER executado com sucesso.\nTotal de países: {len(paises)}")
    salvar_arquivo(RELATORIO_FILE, gerar_relatorio(paises))

if __name__ == "__main__":
    main()
